# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options


before_script:
  - cp .env.example .env
  - export USR=${UID}
  - export GRP=${GID}
  - docker-compose -f ./Docker/docker-compose.yml down
  - docker image prune -f

cache:
    paths:
      - node_modules/
      - vendor

stages:
  - build
  - test
  - deploy

after_script:
  - echo "After script section"
  - echo "For example you might do some cleanup here"

build1:
  stage: build
  script:
    - echo "Do your build here"

test1:
  stage: test
  script:
    - echo "Do a test here"
    - echo "For example run a test suite"


deploy:
  stage: deploy
  tags: 
    - deploy
  script:
    - docker-compose -f ./Docker/docker-compose.yml up -d
    - docker-compose -f ./Docker/docker-compose.yml run php composer install --no-dev
    - docker-compose -f ./Docker/docker-compose.yml run php php artisan migrate
