# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options


cache:
    paths:
      - node_modules/
      - vendor

stages:
  - build

build:
  stage: build
  tags:
    - master
  only:
    - master
  before_script:
  - cp .env.example .env
  - export USR=${UID}
  - export GRP=${GID}
  - docker network prune -f
  - docker-compose -f ./Docker/production.yml down
  - docker system prune -f
  script:
    - docker-compose -f ./Docker/production.yml up -d
    - docker-compose -f ./Docker/production.yml exec -T php composer install --no-dev
    - docker-compose -f ./Docker/production.yml exec -T php php artisan key:generate
    - docker-compose -f ./Docker/production.yml exec -T php php artisan down
    - docker-compose -f ./Docker/production.yml exec -T php php artisan env:set db_host $DB_HOST
    - docker-compose -f ./Docker/production.yml exec -T php php artisan env:set db_username $DB_USERNAME
    - docker-compose -f ./Docker/production.yml exec -T php php artisan env:set db_password $DB_PASSWORD
    - docker-compose -f ./Docker/production.yml exec -T php php artisan env:set app_url $APP_URL
    - docker-compose -f ./Docker/production.yml exec -T php php artisan migrate
    - docker-compose -f ./Docker/production.yml exec -T php php artisan env:set app_env production
    - docker-compose -f ./Docker/production.yml exec -T php php artisan env:set app_debug false
    - docker-compose -f ./Docker/production.yml exec -T php php artisan up

