version: "3"

networks:
  educatm:

volumes:
  educatm-db:    

services:
  nginx:
    image: nginx:stable-alpine
    container_name: educatm-nginx
    restart: unless-stopped    
    ports:
      - "80:80"
    volumes:
      - ./../:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - educatm

  php:
    image: dockerhub.cwd.at/docker/php/fpm:7.4.4
    working_dir: /var/www/html
    user: "${USR}:${GRP}"
    container_name: educatm-php
    restart: unless-stopped
    volumes:
      - ./../:/var/www/html
    networks:
      - educatm  